### ISSUE TITLE
Time issues with Google servo 

### ISSUE THREAD

**Issue by lukasz-hajec** [adamgene/fwupd#1]
Hi,

I am attaching log where first fwupdtool call is used with fwupd compiled from main today, second one is from branch available here https://github.com/semihalf-hajec-lukasz/fwupd/tree/hajec_no_time_issue where problem do not occur. 
In first part of log (lines 55-56) you can observe the problem. Hope it can help with solving the problem.

[fwupd_time_issues.txt](https://github.com/adamgene/fwupd/files/8471670/fwupd_time_issues.txt)

**Comment by adamgene** [comment]
Can you post the log of firmware update to compare the time cost? I am afraid of that will have the same problem.

**Comment by lukasz-hajec** [comment]
Hi,
As I have some problems with getting firmware from remote, I update it this way  
`sudo fwupdtool -v --plugins genesys install ../../../66552782cefed23bde5dc95909ac128159d7549fa8cbb13c1d150f0a34a568d4-GenesysLogic_GL3590_64.15.cab` 
so attaching logs form it - indeed same problem is observed.
[fwupd_time_update.txt](https://github.com/adamgene/fwupd/files/8474686/fwupd_time_update.txt)

**Comment by adamgene** [comment]
That is not normal to take 39s to complete update firmware. I think the transaction between USB host to device has something wrong.

Can you post the log of `lsusb`? I will modify genesys.quirk and code for you to test by USB3.

---
line 234
```
15:59:51:0907 FuPlugin             superclassed write_firmware(genesys)
Decompressing…           [   -                                   ]15:59:51:0923 FuDevice             installing onto 1f914e619b232dc4da68ec3389b98b20163003a2:
<firmware>
  <data size="0xa000">.w..'.GLHUB..f.W</data>
</firmware>

Writing…                 [*****                                  ] 4 minutes remaining…16:00:30:0941 FuHistory            modifying device Servo Dock [1f914e619b232dc4da68ec3389b98b20163003a2]
16:00:30:0950 FuHistory            modifying device Servo Dock [1f914e619b232dc4da68ec3389b98b20163003a2]
```

**Comment by adamgene** [comment]
Please add below into `genesys.quirk` to test by USB3.

```
[USB\VID_05E3&PID_0625]
Plugin = genesys

# Google Servo Dock
[USB\VID_05E3&PID_0625&VENDOR_GOOGLE&IC_359010&BONDING_6A&PORTNUM_3235&VENDORSUP_E8A9A9E4-6C17-5F9C-B7BD-CDA49FE66D75]
Name = Servo Dock

[USB\VID_05E3&PID_0625&VENDOR_GOOGLE&IC_359010&BONDING_6A&PORTNUM_25&VENDORSUP_E8A9A9E4-6C17-5F9C-B7BD-CDA49FE66D75]
Name = Servo Dock
```

**Comment by lukasz-hajec** [comment]
[lsusb.txt](https://github.com/adamgene/fwupd/files/8480436/lsusb.txt)
- verbose mode, both USB2 and USB3 hubs are visible, let me know if you need some different details

[usb3_hajec_branch.txt](https://github.com/adamgene/fwupd/files/8480438/usb3_hajec_branch.txt)
- please note that I also modified .cab archive as it was not compatible with USB3 GUID, hope I did it okey, but not sure
- some errors are reported, but it looks like in the end firmware is updated via USB3 and it is faster indeed

[usb3_main_branch.txt](https://github.com/adamgene/fwupd/files/8480493/usb3_main_branch.txt)
- updating via USB3 using main branch + quirk changes is not possible, the USB3 device is not visible due to some error and I cant use its ID to command
`fwupdtool ... install [file] [device-id]`

**Comment by adamgene** [comment]
`usb3_main_branch.txt`
10:07:00:0138 FuEngine             failed to add device usb:02:00:03: error reading flash at 0x2400: transfer timed out

This is strange. Please comment the code as below, then test get-devices 5 times. I want to check it is random appear or not.
```
# [USB\VID_05E3&PID_0610]
# Plugin = genesys
```

---
`usb3_hajec_branch.txt`
We can take a slow step. In the main branch I call fu_genesys_usbhub_device_read_flash() to verify firmware integrity. This can help us to test the USB throughput.

**Comment by adamgene** [comment]
`lsusb.txt`
Please use `sudo lsusb -d 05e3: -v` and post again. Thanks.

**Comment by lukasz-hajec** [comment]
> Please use sudo lsusb -d 05e3: -v and post again. Thanks.

[lsusb_new.txt](https://github.com/adamgene/fwupd/files/8480903/lsusb_new.txt)

**Comment by lukasz-hajec** [comment]
> Please comment the code as below, then test get-devices 5 times. I want to check it is random appear or not.

[get_devices_new.txt](https://github.com/adamgene/fwupd/files/8480942/get_devices_new.txt)
- I did even more tries and some replugs, indeed it looks random 

- - -


> usb3_hajec_branch.txt
We can take a slow step. In the main branch I call fu_genesys_usbhub_device_read_flash() to verify firmware integrity. This can help us to test the USB throughput.

do you want me to do some next steps here?

**Comment by adamgene** [comment]
> [lsusb_new.txt](https://github.com/adamgene/fwupd/files/8480903/lsusb_new.txt)

It seems nothing wrong.

---

> do you want me to do some next steps here?

We must fix the random failed first.

---

> [get_devices_new.txt](https://github.com/adamgene/fwupd/files/8480942/get_devices_new.txt)
> 
> * I did even more tries and some replugs, indeed it looks random

Try plug-in a device on any DFP of Hub and test again. I guess the `g_usb_device_control_transfer()` has something wrong.

**Comment by lukasz-hajec** [comment]
> Try plug-in a device on any DFP of Hub and test again. I guess the g_usb_device_control_transfer() has something wrong.

[usb_devic_pluged.txt](https://github.com/adamgene/fwupd/files/8481208/usb_devic_pluged.txt)
 
I plugged usb memory stick, you can see it at the beginnig of the log. Behavior looks similar as earlier.

**Comment by adamgene** [comment]
> I plugged usb memory stick, you can see it at the beginnig of the log. Behavior looks similar as earlier.

Please test on another laptop and `servo dock`. Sorry to bother you, currently I cannot identify the issue is on the device or host. I will check it and get something help in-house. Could I ask the `circuit diagram` between the hub and the flash??

**Comment by lukasz-hajec** [comment]
> Please test on another laptop and servo dock 

I will try to test it tomorrow, at least different servo dock. Different laptop can take me some more time, generally we are using fwupd inside chroot if it changes something.

> Could I ask the circuit diagram between the hub and the flash??

I think so, but please provide me your email.

**Comment by adamgene** [comment]
> I think so, but please provide me your email.

My email: `Adam.Chen@genesyslogic.com.tw`, please CC to `Yihsun.Wu@genesyslogic.com.tw` too. Thanks.

**Comment by adamgene** [comment]
I checked the diagram and it looks fine.
We should capture the USB data to analyze the issue. Do you have a `USB analyzer` HW to capture? Otherwise I suggest using the [Wireshark](https://wiki.wireshark.org/CaptureSetup/USB) SW, it also has `tshark` CLI.

**Comment by lukasz-hajec** [comment]
I done some tests with different servo units and results are interesting.
 
Different servo in PVT version has the same behaviour while `get-devices` - USB2 takes ~18s, USB3 randomly reports these errors. 
Different servo in earlier revision, which scheme I would share via email - USB2 takes ~1s, USB3 no errors, short time in 20+ retires.

I could not spot significant differences between these schemes, but please take a look, you can see more probably. 

Can FW version on hub itself do any difference here? 

---

> We should capture the USB data to analyze the issue. Do you have a USB analyzer HW to capture? Otherwise I suggest using the [Wireshark](https://wiki.wireshark.org/CaptureSetup/USB) SW, it also has tshark CLI.

I dont have hardware analyzer, so we can try with Wireshark, but I dont have experience using it and I am not sure what do you exactly need, so let me know. For a starting point I am attaching log (via email as github dont allow these files) with random capture, there are frames from attaching servo etc.

**Comment by lukasz-hajec** [comment]
If it would not be a problem for you I propose to switch entirely to email communication.
